[project]
name = "chessengine"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.7"
dependencies = [
    "keras>=2.11.0",
    "pygame>=2.6.1",
    "tensorflow>=2.6.1",
]
